VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "KeyValuePair"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'------------------------------------------------------------------------------
' @class KeyValuePair
' @desc Unrestricted class just to hold pairs of values together and permit
'   Dictionary object updating
' @version 1.0
' @author http://www.sysmod.com/
'------------------------------------------------------------------------------
Option Explicit

Public Key As String
Public Value As Variant
